import Percolation.Literature.BernoulliPercolation
import Percolation.Literature.PercolationEvents
import Percolation.Util.Linter

/-!
# Disjoint edge sets are independent; closing `k` edges costs a factor `(1 - p)^k`

Two tools of Bernoulli bond percolation
`P_p = bondPercolation G p` (a product measure, Grimmett, *Percolation*, 2nd ed. (1999), §1.3
p. 10, `P_p = ∏_e μ_e`), written for the finite-size arguments of §7.2–§7.3 (Lemma (7.9),
(7.15)–(7.16), p. 151; Lemma (7.36), pp. 165–167) on the way to
`Percolation.Literature.BarskyGrimmettNewman1991_Z3` (`θ_ℍ(p_c) = 0`, Thm. (7.35)):

* `edgeSigma S` — the σ-algebra generated by the states of the edges in `S ⊆ Sym2 V`
  (arbitrary, possibly infinite), and `DeterminedBy.measurableSet_edgeSigma`: a measurable event
  determined by `S` (`DeterminedBy A S`, `PercolationEvents.lean`) is `edgeSigma S`-measurable;
* `bondPercolation_indep_edgeSigma` — for DISJOINT `S, T ⊆ Sym2 V` the σ-algebras
  `edgeSigma S`, `edgeSigma T` are independent under `P_p` (Mathlib's `indep_iSup_of_disjoint`
  applied to the independent edge indicators, `bondPercolation_indep_holds`), whence
  `bondPercolation_inter_of_disjoint`: `P_p(A ∩ B) = P_p(A) P_p(B)` for measurable `A`, `B`
  determined by disjoint edge sets (Grimmett 1999, §2.2; used on p. 167: "this last event is
  conditionally independent of the states of all edges in `B(l, H₁(l) - 1)`");
* `le_bondPercolation_real_forall_notMem` — all edges of a finite set `F` are closed with
  probability `∏_{e ∈ F} (1 - p 1_{e ∈ E(G)}) ≥ (1 - p)^{|F|}`;
* `bondPercolation_finiteEnergy` — **closing at most `k` conditionally specified edges costs at
  most a factor `(1 - p)^k`** (the mechanism of Grimmett's (7.16), p. 151:
  "`P_p(|U(n)| < l, B(m) ↔ ∞) ≤ P_p(1 ≤ |U(n)| < l) ≤ (1 - p)^{-3l} P_p(U(n+1) = ∅, U(n) ≠ ∅)`
  … we have used the fact that `U(n+1) = ∅` if every edge exiting `∂B(n)` from `U(n)` is
  closed"): if on the event `A` a finite set of edges `Φ(ω)` with `|Φ(ω)| ≤ k` is specified as a
  function of a countably-valued statistic `Ψ(ω)` such that each `A ∩ {Ψ = b}` is determined by
  a set `S` of edges disjoint from `Φ`, then `(1 - p)^k P_p(A) ≤ P_p(A ∩ {all edges of Φ closed})`;
* `tendsto_measure_of_pairwise_disjoint` — pairwise disjoint events have probabilities tending
  to `0` along `Filter.cofinite` (the "`→ 0 as n → ∞`" of (7.16), the events
  `{U(n+1) = ∅, U(n) ≠ ∅}` being disjoint for distinct `n`);
* `bondPercolation_inter_memDep_eq_tsum` — the general conditional-independence
  decomposition behind the finite-energy lemma, with value-dependent determining sets:
  if `A ∩ {Ψ = b}` is determined by `S b` and the event `E b` by `T b`, with `S(Ψ ω)`, `T(Ψ ω)`
  disjoint on `A`, then `P_p(A ∩ {ω ∈ E(Ψ ω)}) = Σ_b P_p(A ∩ {Ψ = b}) · P_p(E b)`, whence the
  two-sided bounds `bondPercolation_real_inter_memDep_ge/le` (`q P(A) ≤ P(A ∩ {ω ∈ E(Ψ ω)}) ≤ q' P(A)`
  when `q ≤ P(E b) ≤ q'` on `A`). This is the form needed on p. 167 of Grimmett 1999 ("given `N₂`
  points `z` in `T(l, H₁(l) - 1)`, there is by (7.40) at least probability `1 - ε` that `M` or more
  of the edges `⟨z, z + (0,0,1)⟩` are open (… conditionally independent of the states of all
  edges in `B(l, H₁(l) - 1)`)") and on p. 168 ((7.39): the squares `b(x)`, `x ∈ N`, are seeds
  independently of the interior).

## References

* G. Grimmett, *Percolation*, 2nd ed., Grundlehren 321, Springer 1999, §1.3 p. 10, §2.2,
  §7.2 (7.15)–(7.16) p. 151, §7.3 pp. 165–167.
-/

noncomputable section

namespace Percolation.Literature

open MeasureTheory ProbabilityTheory Filter unitInterval
open scoped ENNReal Topology

variable {V : Type*}

/-! ## The σ-algebra of a set of edges -/

/-- The σ-algebra `σ(S)` on bond configurations generated by the states `1_{e ∈ ω}` of the edges
`e ∈ S` (Grimmett 1999, §2.2 / p. 168 (iv): "measurable on the σ-field generated by the set of
states of edges …"). [cite: GrimmettPercolation1999, §7.3 p. 168 (iv)] -/
@[reducible] def edgeSigma (S : Set (Sym2 V)) : MeasurableSpace (BondConfig V) :=
  ⨆ e ∈ S, MeasurableSpace.comap (fun ω : BondConfig V => e ∈ ω) ⊤

/-- The one-edge σ-algebra is coarser than the product σ-algebra. [folklore] -/
theorem comap_mem_le (e : Sym2 V) :
    MeasurableSpace.comap (fun ω : BondConfig V => e ∈ ω) ⊤ ≤
      (Set.instMeasurableSpace : MeasurableSpace (BondConfig V)) :=
  (measurable_set_mem e).comap_le

/-- Restriction to `S`, `ω ↦ ω ∩ S`, is measurable from `σ(S)` to the product σ-algebra
(stated as an inequality of σ-algebras). [folklore] -/
theorem comap_inter_le_edgeSigma (S : Set (Sym2 V)) :
    MeasurableSpace.comap (fun ω : BondConfig V => ω ∩ S) Set.instMeasurableSpace ≤
      edgeSigma S := by
  have hpi : (Set.instMeasurableSpace : MeasurableSpace (BondConfig V)) =
      ⨆ e : Sym2 V, MeasurableSpace.comap (fun ω : BondConfig V => e ∈ ω) ⊤ := rfl
  rw [hpi, MeasurableSpace.comap_iSup]
  refine iSup_le fun e => ?_
  rw [MeasurableSpace.comap_comp]
  by_cases he : e ∈ S
  · have : ((fun ω : BondConfig V => e ∈ ω) ∘ fun ω : BondConfig V => ω ∩ S) =
        fun ω => e ∈ ω := by
      funext ω
      exact propext ⟨fun h => h.1, fun h => ⟨h, he⟩⟩
    rw [this]
    exact le_iSup₂ (f := fun e (_ : e ∈ S) =>
      MeasurableSpace.comap (fun ω : BondConfig V => e ∈ ω) ⊤) e he
  · have : ((fun ω : BondConfig V => e ∈ ω) ∘ fun ω : BondConfig V => ω ∩ S) =
        fun _ => False := by
      funext ω
      exact propext ⟨fun h => he h.2, False.elim⟩
    rw [this, MeasurableSpace.comap_const]
    exact bot_le

/-- Restriction to `S`, `ω ↦ ω ∩ S`, is measurable from `σ(S)` to the product σ-algebra.
[folklore] -/
theorem measurable_inter_edgeSigma (S : Set (Sym2 V)) :
    @Measurable (BondConfig V) (BondConfig V) (edgeSigma S) Set.instMeasurableSpace
      fun ω => ω ∩ S := by
  rw [measurable_iff_comap_le]
  exact comap_inter_le_edgeSigma S

/-- **A measurable event determined by the edges in `S` is `σ(S)`-measurable.** (It is the
preimage of itself under the `σ(S)`-measurable restriction `ω ↦ ω ∩ S`.)
[cite: GrimmettPercolation1999, §7.3 p. 168 (iv)] -/
theorem DeterminedBy.measurableSet_edgeSigma {A : Set (BondConfig V)} {S : Set (Sym2 V)}
    (hA : DeterminedBy A S) (hAm : MeasurableSet A) : MeasurableSet[edgeSigma S] A := by
  have hAeq : A = (fun ω : BondConfig V => ω ∩ S) ⁻¹' A := by
    ext ω
    exact (determinedBy_iff A S).1 hA ω (ω ∩ S) (by rw [Set.inter_assoc, Set.inter_self])
  rw [hAeq]
  exact measurable_inter_edgeSigma S hAm

/-! ## Independence of disjoint sets of edges -/

/-- **Disjoint sets of edges generate independent σ-algebras under `P_p`** (product measure;
Grimmett 1999, §1.3 p. 10, §2.2). [cite: GrimmettPercolation1999, §1.3 p. 10 (product measure)] -/
theorem bondPercolation_indep_edgeSigma [Countable V] (G : SimpleGraph V) (p : unitInterval)
    {S T : Set (Sym2 V)} (hST : Disjoint S T) :
    Indep (edgeSigma S) (edgeSigma T) (bondPercolation G p) := by
  have h := bondPercolation_indep_holds G p
  rw [← iIndep_comap_mem_iff] at h
  exact indep_iSup_of_disjoint (fun e => comap_mem_le e) h hST

/-- **Events determined by disjoint sets of edges are independent**: `P_p(A ∩ B) = P_p(A) P_p(B)`
for measurable `A`, `B` determined by disjoint (possibly infinite) edge sets `S`, `T`
(Grimmett 1999, §2.2; §7.3 p. 167). [cite: GrimmettPercolation1999, §1.3 p. 10 (product measure)] -/
theorem bondPercolation_inter_of_disjoint [Countable V] (G : SimpleGraph V) (p : unitInterval)
    {S T : Set (Sym2 V)} (hST : Disjoint S T) {A B : Set (BondConfig V)} (hA : DeterminedBy A S)
    (hB : DeterminedBy B T) (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    bondPercolation G p (A ∩ B) = bondPercolation G p A * bondPercolation G p B :=
  (Indep_iff _ _ _).1 (bondPercolation_indep_edgeSigma G p hST) A B
    (hA.measurableSet_edgeSigma hAm) (hB.measurableSet_edgeSigma hBm)

/-- Real-valued form of `bondPercolation_inter_of_disjoint`. [cite: GrimmettPercolation1999, §1.3 p. 10 (product measure)] -/
theorem bondPercolation_real_inter_of_disjoint [Countable V] (G : SimpleGraph V) (p : unitInterval)
    {S T : Set (Sym2 V)} (hST : Disjoint S T) {A B : Set (BondConfig V)} (hA : DeterminedBy A S)
    (hB : DeterminedBy B T) (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    (bondPercolation G p).real (A ∩ B) =
      (bondPercolation G p).real A * (bondPercolation G p).real B := by
  simp only [measureReal_def]
  rw [bondPercolation_inter_of_disjoint G p hST hA hB hAm hBm, ENNReal.toReal_mul]

/-! ## Closed edges -/

/-- The event "every edge of `F` is closed" is determined by `F`. [folklore] -/
theorem determinedBy_forall_notMem (F : Finset (Sym2 V)) :
    DeterminedBy {ω : BondConfig V | ∀ e ∈ F, e ∉ ω} (↑F : Set (Sym2 V)) := by
  rw [determinedBy_iff]
  intro ω ω' h
  simp only [Set.mem_setOf_eq]
  constructor
  · intro hω e he he'
    exact hω e he ((Set.ext_iff.1 h e).2 ⟨he', Finset.mem_coe.2 he⟩).1
  · intro hω' e he heω
    exact hω' e he ((Set.ext_iff.1 h e).1 ⟨heω, Finset.mem_coe.2 he⟩).1

/-- The event "every edge of the finite set `F` is closed" is measurable. [folklore] -/
theorem measurableSet_forall_notMem (F : Finset (Sym2 V)) :
    MeasurableSet {ω : BondConfig V | ∀ e ∈ F, e ∉ ω} := by
  have : {ω : BondConfig V | ∀ e ∈ F, e ∉ ω} = ⋂ e ∈ F, {ω | e ∉ ω} := by
    ext ω; simp
  rw [this]
  exact MeasurableSet.biInter F.countable_toSet fun e _ => measurableSet_notMem e

/-- **All edges of a finite set `F` are closed with probability at least `(1 - p)^{|F|}`**
(exactly `∏_{e ∈ F} (1 - p 1_{e ∈ E(G)})`; Grimmett 1999, §1.3, product measure).
[cite: GrimmettPercolation1999, §1.3 p. 10 (product measure)] -/
theorem le_bondPercolation_real_forall_notMem (G : SimpleGraph V) (p : unitInterval)
    (F : Finset (Sym2 V)) :
    (1 - (p : ℝ)) ^ F.card ≤ (bondPercolation G p).real {ω | ∀ e ∈ F, e ∉ ω} := by
  classical
  have hpre : (fun q : Sym2 V → Prop => {i | q i}) ⁻¹' {ω : BondConfig V | ∀ e ∈ F, e ∉ ω}
      = Set.pi (F : Set (Sym2 V)) (fun _ => {False}) := by
    ext q
    simp only [Set.mem_preimage, Set.mem_setOf_eq, Set.mem_pi, Finset.mem_coe,
      Set.mem_singleton_iff, eq_iff_iff, iff_false]
  rw [measureReal_def, bondPercolation, setBernoulli_apply', hpre,
    Measure.infinitePi_pi _ (fun _ _ => MeasurableSet.of_discrete), ENNReal.toReal_prod,
    ← Finset.prod_const]
  refine Finset.prod_le_prod (fun _ _ => sub_nonneg.2 p.2.2) fun e _ => ?_
  have h1 : ((toNNReal (σ p) : ℝ≥0∞)) ≤ (toNNReal p • Measure.dirac (e ∈ G.edgeSet) +
      toNNReal (σ p) • Measure.dirac False : Measure Prop) {False} := by
    rw [Measure.coe_add, Pi.add_apply, Measure.coe_nnreal_smul_apply,
      Measure.coe_nnreal_smul_apply, Measure.dirac_apply_of_mem (Set.mem_singleton False),
      mul_one]
    exact le_add_self
  have h2 := ENNReal.toReal_mono (measure_ne_top _ _) h1
  rwa [ENNReal.coe_toReal, coe_toNNReal, coe_symm_eq] at h2

/-- `ℝ≥0∞` form: `ENNReal.ofReal ((1 - p)^{|F|}) ≤ P_p(all edges of F closed)`.
[cite: GrimmettPercolation1999, §1.3 p. 10 (product measure)] -/
theorem le_bondPercolation_forall_notMem (G : SimpleGraph V) (p : unitInterval)
    (F : Finset (Sym2 V)) :
    ENNReal.ofReal ((1 - (p : ℝ)) ^ F.card) ≤ bondPercolation G p {ω | ∀ e ∈ F, e ∉ ω} := by
  rw [← ENNReal.ofReal_toReal (measure_ne_top _ _)]
  exact ENNReal.ofReal_le_ofReal (le_bondPercolation_real_forall_notMem G p F)

/-! ## Finite energy: closing at most `k` specified edges costs at most `(1 - p)^k` -/

/-- **Finite-energy / local-modification inequality** (the mechanism of Grimmett 1999, (7.16),
p. 151, and of its uses on pp. 165–167). Let `A` be an event, `Ψ` a statistic of the
configuration with countably many values, and `φ b` a finite set of edges attached to the value
`b`. Suppose that for every value `b` the event `A ∩ {Ψ = b}` is measurable and determined by
a set `S` of edges, that on `A` the edges `φ(Ψ(ω))` avoid `S`, and that `|φ(Ψ(ω))| ≤ k` on `A`.
Then `(1 - p)^k · P_p(A) ≤ P_p(A ∩ {every edge of φ(Ψ(ω)) is closed})`: conditionally on
`A ∩ {Ψ = b}` the edges `φ b` are still independent `Bernoulli`, and all closed with probability
`≥ (1 - p)^k`. [cite: GrimmettPercolation1999, §7.2 (7.16) p. 151] -/
theorem bondPercolation_finiteEnergy [Countable V] {β : Type*} [Countable β] (G : SimpleGraph V)
    (p : unitInterval) {A : Set (BondConfig V)} (S : Set (Sym2 V)) (Ψ : BondConfig V → β)
    (φ : β → Finset (Sym2 V)) (k : ℕ)
    (hdet : ∀ b, DeterminedBy (A ∩ Ψ ⁻¹' {b}) S) (hmeas : ∀ b, MeasurableSet (A ∩ Ψ ⁻¹' {b}))
    (hdisj : ∀ ω ∈ A, Disjoint (↑(φ (Ψ ω)) : Set (Sym2 V)) S)
    (hcard : ∀ ω ∈ A, (φ (Ψ ω)).card ≤ k) :
    ENNReal.ofReal ((1 - (p : ℝ)) ^ k) * bondPercolation G p A ≤
      bondPercolation G p (A ∩ {ω | ∀ e ∈ φ (Ψ ω), e ∉ ω}) := by
  classical
  -- decompose along the values of `Ψ`
  have hA : A = ⋃ b, (A ∩ Ψ ⁻¹' {b}) := by
    ext ω; simp
  have hAC : A ∩ {ω | ∀ e ∈ φ (Ψ ω), e ∉ ω} =
      ⋃ b, (A ∩ Ψ ⁻¹' {b}) ∩ {ω | ∀ e ∈ φ b, e ∉ ω} := by
    ext ω
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iUnion, Set.mem_preimage,
      Set.mem_singleton_iff]
    constructor
    · rintro ⟨hω, hc⟩
      exact ⟨Ψ ω, ⟨hω, rfl⟩, hc⟩
    · rintro ⟨b, ⟨hω, rfl⟩, hc⟩
      exact ⟨hω, hc⟩
  have hdisjA : Pairwise (Function.onFun Disjoint fun b => A ∩ Ψ ⁻¹' {b}) := by
    intro b b' hbb'
    rw [Function.onFun, Set.disjoint_left]
    rintro ω ⟨-, hb⟩ ⟨-, hb'⟩
    exact hbb' (hb.symm.trans hb')
  have hdisjAC : Pairwise (Function.onFun Disjoint
      fun b => (A ∩ Ψ ⁻¹' {b}) ∩ {ω | ∀ e ∈ φ b, e ∉ ω}) := fun b b' hbb' =>
    (hdisjA hbb').mono Set.inter_subset_left Set.inter_subset_left
  -- termwise inequality
  have hterm : ∀ b, ENNReal.ofReal ((1 - (p : ℝ)) ^ k) * bondPercolation G p (A ∩ Ψ ⁻¹' {b}) ≤
      bondPercolation G p ((A ∩ Ψ ⁻¹' {b}) ∩ {ω | ∀ e ∈ φ b, e ∉ ω}) := by
    intro b
    rcases (A ∩ Ψ ⁻¹' {b}).eq_empty_or_nonempty with hemp | ⟨ω₀, hω₀⟩
    · simp [hemp]
    · have hb : Ψ ω₀ = b := hω₀.2
      have hdj : Disjoint S (↑(φ b) : Set (Sym2 V)) := by
        have := hdisj ω₀ hω₀.1
        rw [hb] at this
        exact this.symm
      have hk : (φ b).card ≤ k := by
        have := hcard ω₀ hω₀.1
        rwa [hb] at this
      rw [bondPercolation_inter_of_disjoint G p hdj (hdet b)
        (determinedBy_forall_notMem (φ b)) (hmeas b) (measurableSet_forall_notMem (φ b)),
        mul_comm]
      refine mul_le_mul_right ?_ _
      calc ENNReal.ofReal ((1 - (p : ℝ)) ^ k)
          ≤ ENNReal.ofReal ((1 - (p : ℝ)) ^ (φ b).card) :=
            ENNReal.ofReal_le_ofReal (pow_le_pow_of_le_one (sub_nonneg.2 p.2.2)
              (sub_le_self _ p.2.1) hk)
        _ ≤ bondPercolation G p {ω | ∀ e ∈ φ b, e ∉ ω} := by
            simpa using le_bondPercolation_forall_notMem G p (φ b)
  -- sum up
  have hmeasC : ∀ b, MeasurableSet ((A ∩ Ψ ⁻¹' {b}) ∩ {ω : BondConfig V | ∀ e ∈ φ b, e ∉ ω}) :=
    fun b => (hmeas b).inter (measurableSet_forall_notMem (φ b))
  calc ENNReal.ofReal ((1 - (p : ℝ)) ^ k) * bondPercolation G p A
      = ENNReal.ofReal ((1 - (p : ℝ)) ^ k) * ∑' b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := by
        conv_lhs => rw [hA]
        rw [measure_iUnion hdisjA hmeas]
    _ = ∑' b, ENNReal.ofReal ((1 - (p : ℝ)) ^ k) * bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := by
        rw [ENNReal.tsum_mul_left]
    _ ≤ ∑' b, bondPercolation G p ((A ∩ Ψ ⁻¹' {b}) ∩ {ω | ∀ e ∈ φ b, e ∉ ω}) :=
        ENNReal.tsum_le_tsum hterm
    _ = bondPercolation G p (A ∩ {ω | ∀ e ∈ φ (Ψ ω), e ∉ ω}) := by
        rw [hAC, measure_iUnion hdisjAC hmeasC]

/-- Real-valued form of the finite-energy inequality: `(1 - p)^k P_p(A) ≤ P_p(A ∩ {φ(Ψ) closed})`.
[cite: GrimmettPercolation1999, §7.2 (7.16) p. 151] -/
theorem bondPercolation_real_finiteEnergy [Countable V] {β : Type*} [Countable β]
    (G : SimpleGraph V) (p : unitInterval) {A : Set (BondConfig V)} (S : Set (Sym2 V))
    (Ψ : BondConfig V → β) (φ : β → Finset (Sym2 V)) (k : ℕ)
    (hdet : ∀ b, DeterminedBy (A ∩ Ψ ⁻¹' {b}) S) (hmeas : ∀ b, MeasurableSet (A ∩ Ψ ⁻¹' {b}))
    (hdisj : ∀ ω ∈ A, Disjoint (↑(φ (Ψ ω)) : Set (Sym2 V)) S)
    (hcard : ∀ ω ∈ A, (φ (Ψ ω)).card ≤ k) :
    (1 - (p : ℝ)) ^ k * (bondPercolation G p).real A ≤
      (bondPercolation G p).real (A ∩ {ω | ∀ e ∈ φ (Ψ ω), e ∉ ω}) := by
  have h := bondPercolation_finiteEnergy G p S Ψ φ k hdet hmeas hdisj hcard
  have hk : 0 ≤ (1 - (p : ℝ)) ^ k := pow_nonneg (sub_nonneg.2 p.2.2) k
  simp only [measureReal_def]
  rw [← ENNReal.toReal_ofReal hk, ← ENNReal.toReal_mul]
  exact ENNReal.toReal_mono (measure_ne_top _ _) h

/-! ## Disjoint events have vanishing probabilities -/

/-- **Pairwise disjoint events have probabilities tending to `0`** (along the cofinite filter of
the index type; for `ℕ` this is `n → ∞`): their probabilities are summable (bounded by the total
mass). This is the "`→ 0 as n → ∞`" in Grimmett's (7.16), the events `{U(n+1) = ∅, U(n) ≠ ∅}`
being disjoint for distinct `n`. [cite: GrimmettPercolation1999, §7.2 (7.16) p. 151] -/
theorem tendsto_measure_of_pairwise_disjoint {Ω ι : Type*} [MeasurableSpace Ω] [Countable ι]
    (μ : Measure Ω) [IsFiniteMeasure μ] {D : ι → Set Ω} (hD : ∀ i, MeasurableSet (D i))
    (hdisj : Pairwise (Function.onFun Disjoint D)) :
    Tendsto (fun i => μ (D i)) cofinite (𝓝 0) := by
  apply ENNReal.tendsto_cofinite_zero_of_tsum_ne_top
  rw [← measure_iUnion hdisj hD]
  exact measure_ne_top _ _

/-- The same along `atTop` for events indexed by `ℕ`, in real form: `P(D_n) → 0`.
[cite: GrimmettPercolation1999, §7.2 (7.16) p. 151] -/
theorem tendsto_measureReal_of_pairwise_disjoint {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsFiniteMeasure μ] {D : ℕ → Set Ω} (hD : ∀ n, MeasurableSet (D n))
    (hdisj : Pairwise (Function.onFun Disjoint D)) :
    Tendsto (fun n => μ.real (D n)) atTop (𝓝 0) := by
  have h := tendsto_measure_of_pairwise_disjoint μ hD hdisj
  rw [Nat.cofinite_eq_atTop] at h
  have h' := (ENNReal.tendsto_toReal ENNReal.zero_ne_top).comp h
  rw [ENNReal.toReal_zero] at h'
  exact h'

/-! ## Conditional independence given a countably-valued statistic (value-dependent supports) -/

/-- **Conditional-independence decomposition.** Let `Ψ` be a countably-valued statistic, and for
each value `b` let the event `A ∩ {Ψ = b}` be measurable and determined by the edge set `S b`,
and the event `E b` be measurable and determined by `T b`, where `S (Ψ ω)` and `T (Ψ ω)` are
disjoint for `ω ∈ A`. Then `P_p(A ∩ {ω | ω ∈ E (Ψ ω)}) = Σ_b P_p(A ∩ {Ψ = b}) · P_p(E b)`
(Grimmett 1999, p. 167: "this last event is conditionally independent of the states of all edges
in `B(l, H₁(l) - 1)`"). [cite: GrimmettPercolation1999, §7.3 p. 167] -/
theorem bondPercolation_inter_memDep_eq_tsum [Countable V] {β : Type*} [Countable β]
    (G : SimpleGraph V) (p : unitInterval) {A : Set (BondConfig V)} (S T : β → Set (Sym2 V))
    (Ψ : BondConfig V → β) (E : β → Set (BondConfig V))
    (hdet : ∀ b, DeterminedBy (A ∩ Ψ ⁻¹' {b}) (S b)) (hmeas : ∀ b, MeasurableSet (A ∩ Ψ ⁻¹' {b}))
    (hE : ∀ b, DeterminedBy (E b) (T b)) (hEm : ∀ b, MeasurableSet (E b))
    (hdisj : ∀ ω ∈ A, Disjoint (S (Ψ ω)) (T (Ψ ω))) :
    bondPercolation G p (A ∩ {ω | ω ∈ E (Ψ ω)}) =
      ∑' b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) * bondPercolation G p (E b) := by
  classical
  have hAC : A ∩ {ω | ω ∈ E (Ψ ω)} = ⋃ b, (A ∩ Ψ ⁻¹' {b}) ∩ E b := by
    ext ω
    simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iUnion, Set.mem_preimage,
      Set.mem_singleton_iff]
    constructor
    · rintro ⟨hω, hc⟩
      exact ⟨Ψ ω, ⟨hω, rfl⟩, hc⟩
    · rintro ⟨b, ⟨hω, rfl⟩, hc⟩
      exact ⟨hω, hc⟩
  have hdisjA : Pairwise (Function.onFun Disjoint fun b => (A ∩ Ψ ⁻¹' {b}) ∩ E b) := by
    intro b b' hbb'
    rw [Function.onFun, Set.disjoint_left]
    rintro ω ⟨⟨-, hb⟩, -⟩ ⟨⟨-, hb'⟩, -⟩
    exact hbb' (hb.symm.trans hb')
  rw [hAC, measure_iUnion hdisjA fun b => (hmeas b).inter (hEm b)]
  refine tsum_congr fun b => ?_
  rcases (A ∩ Ψ ⁻¹' {b}).eq_empty_or_nonempty with hemp | ⟨ω₀, hω₀⟩
  · simp [hemp]
  · have hb : Ψ ω₀ = b := hω₀.2
    have hdj : Disjoint (S b) (T b) := by
      have := hdisj ω₀ hω₀.1
      rwa [hb] at this
    exact bondPercolation_inter_of_disjoint G p hdj (hdet b) (hE b) (hmeas b) (hEm b)

/-- **Lower bound**: if `q ≤ P_p(E(Ψ ω))` for `ω ∈ A`, then
`q · P_p(A) ≤ P_p(A ∩ {ω ∈ E(Ψ ω)})` (e.g. p. 167: "the conditional probability in (7.45) is at
least `1 - ε`, whence `P(U(l, H₁(l)) ≥ M) ≥ (1 - 2ε)(1 - ε)`"). [cite: GrimmettPercolation1999, §7.3 p. 167 (7.45)–(7.46)] -/
theorem bondPercolation_real_inter_memDep_ge [Countable V] {β : Type*} [Countable β]
    (G : SimpleGraph V) (p : unitInterval) {A : Set (BondConfig V)} (S T : β → Set (Sym2 V))
    (Ψ : BondConfig V → β) (E : β → Set (BondConfig V))
    (hdet : ∀ b, DeterminedBy (A ∩ Ψ ⁻¹' {b}) (S b)) (hmeas : ∀ b, MeasurableSet (A ∩ Ψ ⁻¹' {b}))
    (hE : ∀ b, DeterminedBy (E b) (T b)) (hEm : ∀ b, MeasurableSet (E b))
    (hdisj : ∀ ω ∈ A, Disjoint (S (Ψ ω)) (T (Ψ ω))) {q : ℝ} (hq0 : 0 ≤ q)
    (hq : ∀ ω ∈ A, q ≤ (bondPercolation G p).real (E (Ψ ω))) :
    q * (bondPercolation G p).real A ≤ (bondPercolation G p).real (A ∩ {ω | ω ∈ E (Ψ ω)}) := by
  classical
  have hA : A = ⋃ b, (A ∩ Ψ ⁻¹' {b}) := by
    ext ω; simp
  have hdisjA : Pairwise (Function.onFun Disjoint fun b => A ∩ Ψ ⁻¹' {b}) := by
    intro b b' hbb'
    rw [Function.onFun, Set.disjoint_left]
    rintro ω ⟨-, hb⟩ ⟨-, hb'⟩
    exact hbb' (hb.symm.trans hb')
  have hterm : ∀ b, ENNReal.ofReal q * bondPercolation G p (A ∩ Ψ ⁻¹' {b}) ≤
      bondPercolation G p (A ∩ Ψ ⁻¹' {b}) * bondPercolation G p (E b) := by
    intro b
    rcases (A ∩ Ψ ⁻¹' {b}).eq_empty_or_nonempty with hemp | ⟨ω₀, hω₀⟩
    · simp [hemp]
    · rw [mul_comm]
      refine mul_le_mul_right ?_ _
      have h1 := hq ω₀ hω₀.1
      rw [hω₀.2] at h1
      calc ENNReal.ofReal q ≤ ENNReal.ofReal ((bondPercolation G p).real (E b)) :=
            ENNReal.ofReal_le_ofReal h1
        _ = bondPercolation G p (E b) := ENNReal.ofReal_toReal (measure_ne_top _ _)
  have hEN : ENNReal.ofReal q * bondPercolation G p A ≤
      bondPercolation G p (A ∩ {ω | ω ∈ E (Ψ ω)}) := by
    calc ENNReal.ofReal q * bondPercolation G p A
        = ENNReal.ofReal q * ∑' b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := by
          conv_lhs => rw [hA]
          rw [measure_iUnion hdisjA hmeas]
      _ = ∑' b, ENNReal.ofReal q * bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := by
          rw [ENNReal.tsum_mul_left]
      _ ≤ ∑' b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) * bondPercolation G p (E b) :=
          ENNReal.tsum_le_tsum hterm
      _ = bondPercolation G p (A ∩ {ω | ω ∈ E (Ψ ω)}) :=
          (bondPercolation_inter_memDep_eq_tsum G p S T Ψ E hdet hmeas hE hEm hdisj).symm
  simp only [measureReal_def]
  rw [← ENNReal.toReal_ofReal hq0, ← ENNReal.toReal_mul]
  exact ENNReal.toReal_mono (measure_ne_top _ _) hEN

/-- **Upper bound**: if `P_p(E(Ψ ω)) ≤ q` for `ω ∈ A`, then
`P_p(A ∩ {ω ∈ E(Ψ ω)}) ≤ q · P_p(A)` (e.g. p. 168: given the interior, the disjoint squares
`b(x)`, `x ∈ N`, `|N| ≥ N₁`, contain no seed with probability at most `(1 - π)^{N₁}`, (7.39)).
[cite: GrimmettPercolation1999, §7.3 p. 168 (7.39), (7.48)] -/
theorem bondPercolation_real_inter_memDep_le [Countable V] {β : Type*} [Countable β]
    (G : SimpleGraph V) (p : unitInterval) {A : Set (BondConfig V)} (S T : β → Set (Sym2 V))
    (Ψ : BondConfig V → β) (E : β → Set (BondConfig V))
    (hdet : ∀ b, DeterminedBy (A ∩ Ψ ⁻¹' {b}) (S b)) (hmeas : ∀ b, MeasurableSet (A ∩ Ψ ⁻¹' {b}))
    (hE : ∀ b, DeterminedBy (E b) (T b)) (hEm : ∀ b, MeasurableSet (E b))
    (hdisj : ∀ ω ∈ A, Disjoint (S (Ψ ω)) (T (Ψ ω))) {q : ℝ}
    (hq : ∀ ω ∈ A, (bondPercolation G p).real (E (Ψ ω)) ≤ q) :
    (bondPercolation G p).real (A ∩ {ω | ω ∈ E (Ψ ω)}) ≤ q * (bondPercolation G p).real A := by
  classical
  rcases A.eq_empty_or_nonempty with hAemp | ⟨ω₁, hω₁⟩
  · simp [hAemp]
  have hq0 : 0 ≤ q := measureReal_nonneg.trans (hq ω₁ hω₁)
  have hA : A = ⋃ b, (A ∩ Ψ ⁻¹' {b}) := by
    ext ω; simp
  have hdisjA : Pairwise (Function.onFun Disjoint fun b => A ∩ Ψ ⁻¹' {b}) := by
    intro b b' hbb'
    rw [Function.onFun, Set.disjoint_left]
    rintro ω ⟨-, hb⟩ ⟨-, hb'⟩
    exact hbb' (hb.symm.trans hb')
  have hterm : ∀ b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) * bondPercolation G p (E b) ≤
      ENNReal.ofReal q * bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := by
    intro b
    rcases (A ∩ Ψ ⁻¹' {b}).eq_empty_or_nonempty with hemp | ⟨ω₀, hω₀⟩
    · simp [hemp]
    · rw [mul_comm (ENNReal.ofReal q)]
      have h1 := hq ω₀ hω₀.1
      rw [hω₀.2] at h1
      gcongr
      calc bondPercolation G p (E b) = ENNReal.ofReal ((bondPercolation G p).real (E b)) :=
            (ENNReal.ofReal_toReal (measure_ne_top _ _)).symm
        _ ≤ ENNReal.ofReal q := ENNReal.ofReal_le_ofReal h1
  have hEN : bondPercolation G p (A ∩ {ω | ω ∈ E (Ψ ω)}) ≤
      ENNReal.ofReal q * bondPercolation G p A := by
    calc bondPercolation G p (A ∩ {ω | ω ∈ E (Ψ ω)})
        = ∑' b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) * bondPercolation G p (E b) :=
          bondPercolation_inter_memDep_eq_tsum G p S T Ψ E hdet hmeas hE hEm hdisj
      _ ≤ ∑' b, ENNReal.ofReal q * bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := ENNReal.tsum_le_tsum hterm
      _ = ENNReal.ofReal q * ∑' b, bondPercolation G p (A ∩ Ψ ⁻¹' {b}) := by
          rw [ENNReal.tsum_mul_left]
      _ = ENNReal.ofReal q * bondPercolation G p A := by
          conv_rhs => rw [hA]
          rw [measure_iUnion hdisjA hmeas]
  simp only [measureReal_def]
  rw [← ENNReal.toReal_ofReal hq0, ← ENNReal.toReal_mul]
  exact ENNReal.toReal_mono (ENNReal.mul_ne_top ENNReal.ofReal_ne_top (measure_ne_top _ _)) hEN

end Percolation.Literature

end
