import Percolation.Literature.HalfSpaceBrickUp
import Percolation.Literature.InequalitiesProofs
import Percolation.Util.Linter

/-!
# Seeds on the top and sides of the brick: (7.39), (7.48)–(7.50) of Lemma (7.36)

Sixth step of the proof of Lemma (7.36) of Grimmett, *Percolation*, 2nd ed. (1999), §7.3,
pp. 165 and 167–168 (finite-size criterion of the Barsky–Grimmett–Newman theorem
`θ_ℍ(p_c) = 0`), proved here:

> "The number `N₁` has been chosen in such a way that, if we are provided with `M` vertices of
> `S` [resp. `T`], then these include at least `N₁` vertices such that the squares `b(x)` are
> disjoint. We choose `M = M(ε)` sufficiently large that (7.39) [`(1 - π)^{N₁} < ε`, `π` the
> probability that a square is a seed] … If `U ≥ M` then there exists some subset `N` of `T(L,H)`
> such that: (i) `|N| ≥ N₁`; (ii) for all `x ∈ N`, `b(0) ↔ x in B(L,H)*`; (iii) the squares
> `b(x)`, `x ∈ N`, are disjoint; (iv) the set `N` is measurable on the σ-field generated by the
> states of edges having at least one endvertex in the interior of `B(L,H)`. Since the squares
> `b(x)`, `x ∈ N`, do not intersect the interior of `B(L,H)`, we deduce by (7.39) that
> `P(U ≥ M, X = 0) ≤ ε` [(7.48)–(7.49)], where `X = |{x ∈ T(L,H) : b(0) ↔ x in B(L,H)*, b(x) is a
> seed}|`. A similar argument applies to `Y` [(7.50)]."

Contents (coordinates of `HalfSpace.lean`, vertical axis `0`; `b(x) = BGN.assocSquare m L H x`,
`IsSeed`, `HalfSpaceBGN.lean`):

* `bondPercolation_real_biInter_eq_prod` — events determined by pairwise disjoint edge sets are
  jointly independent (product formula; from the two-set case of `FiniteEnergy.lean`);

## References

* G. Grimmett, *Percolation*, 2nd ed., Grundlehren 321, Springer 1999, §7.3, proof of
  Lemma (7.36), p. 165 (`N₁`, (7.39)), pp. 167–168 ((7.48)–(7.50)).
-/

noncomputable section

namespace Percolation.Literature

open MeasureTheory ProbabilityTheory Filter LatticeModels unitInterval
open scoped ENNReal Topology

/-! ## Joint independence of events with pairwise disjoint supports -/

/-- [cite: GrimmettPercolation1999, §2.5 p. 47 (events depending only on the edges in E)] -/
theorem DeterminedBy.biInter {X ι : Type*} (s : Finset ι) {A : ι → Set (Set X)}
    {T : ι → Set X} (h : ∀ i ∈ s, DeterminedBy (A i) (T i)) :
    DeterminedBy (⋂ i ∈ s, A i) (⋃ i ∈ s, T i) :=
  DeterminedBy.iInter fun i => DeterminedBy.iInter fun hi =>
    (h i hi).mono (Set.subset_biUnion_of_mem (u := fun i => T i) hi)

/-- **Events determined by pairwise disjoint edge sets are jointly independent**:
`P_p(⋂_{i ∈ s} A_i) = ∏_{i ∈ s} P_p(A_i)` (product measure; Grimmett 1999, §2.2; induction on
`s` from `bondPercolation_real_inter_of_disjoint`). [cite: GrimmettPercolation1999, §1.3 p. 10 (product measure)] -/
theorem bondPercolation_real_biInter_eq_prod {V ι : Type*} [Countable V] (G : SimpleGraph V)
    (p : unitInterval) (s : Finset ι) (A : ι → Set (BondConfig V)) (T : ι → Set (Sym2 V))
    (hdet : ∀ i ∈ s, DeterminedBy (A i) (T i)) (hmeas : ∀ i ∈ s, MeasurableSet (A i))
    (hdisj : (↑s : Set ι).PairwiseDisjoint T) :
    (bondPercolation G p).real (⋂ i ∈ s, A i) = ∏ i ∈ s, (bondPercolation G p).real (A i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert j s hj ih =>
    rw [Finset.set_biInter_insert, Finset.prod_insert hj]
    have hdet' : ∀ i ∈ s, DeterminedBy (A i) (T i) := fun i hi => hdet i (Finset.mem_insert_of_mem hi)
    have hmeas' : ∀ i ∈ s, MeasurableSet (A i) := fun i hi => hmeas i (Finset.mem_insert_of_mem hi)
    have hdisj' : (↑s : Set ι).PairwiseDisjoint T := hdisj.subset (by simp)
    have hdj : Disjoint (T j) (⋃ i ∈ s, T i) := by
      rw [Set.disjoint_iUnion₂_right]
      intro i hi
      exact hdisj (Finset.mem_insert_self j s) (Finset.mem_insert_of_mem hi) (fun h => hj (h ▸ hi))
    rw [bondPercolation_real_inter_of_disjoint G p hdj (hdet j (Finset.mem_insert_self j s))
      (DeterminedBy.biInter s hdet') (hmeas j (Finset.mem_insert_self j s))
      (MeasurableSet.biInter s.countable_toSet hmeas'), ih hdet' hmeas' hdisj']

end Percolation.Literature

end
