import Percolation.Literature.HalfSpaceHighDimBrickExit
import Percolation.Util.Linter

/-!
# Seed rules on the top and sides of the brick in `ℤ^d`: (7.39), (7.48)–(7.50) of Lemma (7.36)

Sixth step of the bottom-up proof, in every dimension
`d`, of the finite-size criterion of the Barsky–Grimmett–Newman theorem (Grimmett, *Percolation*,
2nd ed. (1999), §7.3, Lemma (7.36) = Barsky–Grimmett–Newman 1991, Prop. 2.1), after its `d = 3`
models `HalfSpaceBrickSeeds.lean` and `CleanSeeds.lean` (generic part). Grimmett, pp. 165,
167–168:

> "The number `N₁` has been chosen in such a way that, if we are provided with `M` vertices of
> `S` [resp. `T`], then these include at least `N₁` vertices such that the squares `b(x)` are
> disjoint. We choose `M = M(ε)` sufficiently large that (7.39) [`(1 - π)^{N₁} < ε`] … If
> `U ≥ M` then there exists some subset `N` of `T(L,H)` such that: (i) `|N| ≥ N₁`; (ii) for all
> `x ∈ N`, `b(0) ↔ x in B(L,H)*`; (iii) the squares `b(x)`, `x ∈ N`, are disjoint; (iv) the set
> `N` is measurable on the σ-field generated by the states of edges having at least one
> endvertex in the interior of `B(L,H)`. Since the squares `b(x)`, `x ∈ N`, do not intersect the
> interior of `B(L,H)`, we deduce by (7.39) that `P(U ≥ M, X = 0) ≤ ε` [(7.48)–(7.49)] … A
> similar argument applies to `Y` [(7.50)]."

As in `CleanSeeds.lean`, the only properties of the map `x ↦ (edges of b(x))` used by this argument
are abstracted into a **seed rule** `E : Site d → Finset (Sym2 (Site d))` which is *valid*
(`BGNd.SeedRuleValid E L H r K`): the rule-edges of a vertex of `T ∪ S` are lattice edges, avoid
the edges of `B(L,H)*`, number at most `K`, are disjoint for distinct `r`-far vertices, and the
rule commutes with the horizontal reflections of the brick. Contents:

* `BGNd.Far r x y` (sup-distance `> r`), the greedy separation `BGNd.exists_separated_subset`
  (a finite `W ⊆ ℤ^d` contains a pairwise `r`-far subset `N` with `|W| ≤ |N| · |B(r)|`,
  `|B(r)| = |box d r|`);
* `BGNd.refl ε` (the reflections `x ↦ (x₀, ε₁x₁, …)`), `BGNd.SeedRuleValid`, `BGNd.Linked`,
  `BGNd.RuleOpen`, `BGNd.okEventR` (`X_ρ ≥ 1` / `Y_{a,τ} ≥ 1`) and the good event
  `BGNd.goodR m L H E` — an ok vertex in each of the `2^{d-1}` top subfacets and each of the
  `(d-1)2^{d-1}` side subfacets — increasing and measurable;
* the seed estimate `BGNd.prob_linked_noOpen_le`: for a statistic `Φ ω ⊆ T ∪ S` of linked
  vertices depending only on the edges of `B(L,H)*`, `P_p(|Φ| ≥ M, no x ∈ Φ has all its
  rule-edges open) ≤ (1 - p^K)^{N₁}` whenever `M ≥ N₁ |B(r)|` (the conditional-independence
  decomposition `bondPercolation_real_inter_memDep_le` of `FiniteEnergy.lean`), specialised to the
  linked top vertices ((7.48)–(7.49)) and to the linked vertices of a facet family ((7.50)).

## References

* G. Grimmett, *Percolation*, 2nd ed., Grundlehren 321, Springer 1999, §7.3, proof of
  Lemma (7.36), p. 165 (`N₁`, (7.39)), pp. 167–168 ((7.48)–(7.50)).
* D. J. Barsky, G. R. Grimmett, C. M. Newman, Probab. Theory Related Fields 90 (1991) 111–148,
  §2 (Lemma 2.6, Cor. 2.7).
-/

noncomputable section

namespace Percolation.Literature

open _root_.MeasureTheory _root_.ProbabilityTheory _root_.Filter LatticeModels unitInterval
open scoped _root_.ENNReal _root_.Topology

namespace BGNd

variable {d : ℕ}

/-! ## Separated subsets -/

/-- `x` and `y` are `r`-far: sup-distance `> r`. [folklore] -/
def Far (r : ℕ) (x y : Site d) : Prop := ∃ i : Fin d, (r : ℤ) < |x i - y i|

/-- `Far` is symmetric. [folklore] -/
theorem far_comm {r : ℕ} {x y : Site d} (h : Far r x y) : Far r y x := by
  obtain ⟨i, hi⟩ := h
  exact ⟨i, by rwa [abs_sub_comm]⟩

/-- A point is not far from itself. [folklore] -/
theorem not_far_self (r : ℕ) (x : Site d) : ¬Far r x x := by
  rintro ⟨i, hi⟩
  simp at hi
  omega

/-- The points of `W` within sup-distance `r` of `x` are at most `|B(r)|` (they inject into the
box `B(r)` by `y ↦ y - x`). [folklore] -/
theorem card_filter_not_far_le (r : ℕ) (x : Site d) (W : Finset (Site d)) [DecidablePred fun y => ¬Far r x y] :
    (W.filter fun y => ¬Far r x y).card ≤ (box d r).card := by
  classical
  refine Finset.card_le_card_of_injOn (fun y => y - x) (fun y hy => ?_) (fun y _ y' _ h => sub_left_injective h)
  rw [Finset.mem_coe, Finset.mem_filter] at hy
  have h := hy.2
  simp only [Far, not_exists, not_lt] at h
  rw [Finset.mem_coe, mem_box]
  intro i
  have := abs_le.1 (h i)
  simp only [Pi.sub_apply]
  constructor <;> omega

/-- **Greedy separation**: every finite `W ⊆ ℤ^d` contains a pairwise `r`-far subset `N` with
`|W| ≤ |N| · |B(r)|` (Grimmett 1999, p. 165: "`M` vertices … include at least `N₁` vertices such
that the squares are disjoint"). [cite: GrimmettPercolation1999, §7.3 p. 165 (N₁)] -/
theorem exists_separated_subset (r : ℕ) (W : Finset (Site d)) :
    ∃ N ⊆ W, (∀ x ∈ N, ∀ y ∈ N, x ≠ y → Far r x y) ∧ W.card ≤ N.card * (box d r).card := by
  classical
  induction hn : W.card using Nat.strong_induction_on generalizing W with
  | _ n ih =>
    rcases W.eq_empty_or_nonempty with rfl | ⟨x, hx⟩
    · refine ⟨∅, Finset.empty_subset _, by simp, ?_⟩
      rw [← hn]; simp
    · set W' := W.filter fun y => Far r x y with hW'
      have hxW' : x ∉ W' := by simp [hW', not_far_self]
      have hlt : W'.card < n := by
        rw [← hn]
        exact Finset.card_lt_card ⟨Finset.filter_subset _ _, fun h => hxW' (h hx)⟩
      obtain ⟨N', hN'W', hfar, hcard⟩ := ih W'.card hlt W' rfl
      refine ⟨insert x N', ?_, ?_, ?_⟩
      · exact Finset.insert_subset hx (hN'W'.trans (Finset.filter_subset _ _))
      · intro a ha b hb hab
        rw [Finset.mem_insert] at ha hb
        have hfarx : ∀ y ∈ N', Far r x y := fun y hy => (Finset.mem_filter.1 (hN'W' hy)).2
        rcases ha with rfl | ha <;> rcases hb with rfl | hb
        · exact absurd rfl hab
        · exact hfarx b hb
        · exact far_comm (hfarx a ha)
        · exact hfar a ha b hb hab
      · have hxN' : x ∉ N' := fun h => hxW' (hN'W' h)
        rw [Finset.card_insert_of_notMem hxN', ← hn]
        have hsplit : W.card ≤ W'.card + (W.filter fun y => ¬Far r x y).card := by
          rw [hW', Finset.card_filter_add_card_filter_not]
        calc W.card ≤ W'.card + (box d r).card := hsplit.trans (Nat.add_le_add_left (card_filter_not_far_le r x W) _)
          _ ≤ N'.card * (box d r).card + (box d r).card := Nat.add_le_add_right hcard _
          _ = (N'.card + 1) * (box d r).card := by ring

/-- `|B(r)| ≥ 1`. [folklore] -/
theorem one_le_card_box (r : ℕ) : 1 ≤ (box d r).card :=
  Finset.card_pos.2 ⟨0, by simp [mem_box]⟩

/-- A pairwise `r`-far subset of `W` with `|W| ≤ |selR| · |B(r)|` (a choice function).
[cite: GrimmettPercolation1999, §7.3 p. 165 (N₁)] -/
def selR (r : ℕ) (W : Finset (Site d)) : Finset (Site d) := Classical.choose (exists_separated_subset r W)

/-- Properties of `selR`. [folklore] -/
theorem selR_spec (r : ℕ) (W : Finset (Site d)) :
    selR r W ⊆ W ∧ (∀ x ∈ selR r W, ∀ y ∈ selR r W, x ≠ y → Far r x y) ∧
      W.card ≤ (selR r W).card * (box d r).card :=
  Classical.choose_spec (exists_separated_subset r W)

/-! ## Rule-edges -/

/-- All edges attached to `x` by the rule `E` are open (for Grimmett's rule: "`b(x)` is a seed").
[cite: GrimmettPercolation1999, §7.3 p. 163 (seed)] -/
def RuleOpen (E : Site d → Finset (Sym2 (Site d))) (x : Site d) (ω : BondConfig (Site d)) : Prop :=
  (↑(E x) : Set (Sym2 (Site d))) ⊆ ω

/-- `RuleOpen` is measurable. [folklore] -/
theorem measurableSet_ruleOpen (E : Site d → Finset (Sym2 (Site d))) (x : Site d) :
    MeasurableSet {ω : BondConfig (Site d) | RuleOpen E x ω} := by
  have : {ω : BondConfig (Site d) | RuleOpen E x ω} = ⋂ e ∈ E x, {ω | e ∈ ω} := by
    ext ω; simp [RuleOpen, Set.subset_def]
  rw [this]
  exact MeasurableSet.biInter (Set.to_countable _) fun e _ => measurableSet_mem e

/-- `RuleOpen E x` is determined by the rule-edges of `x`. [folklore] -/
theorem determinedBy_ruleOpen (E : Site d → Finset (Sym2 (Site d))) (x : Site d) :
    DeterminedBy {ω : BondConfig (Site d) | RuleOpen E x ω} ↑(E x) := by
  rw [determinedBy_iff]
  intro ω ω' h
  simp only [Set.mem_setOf_eq, RuleOpen, Set.subset_def, Finset.mem_coe]
  constructor
  · intro hs e he; exact ((Set.ext_iff.1 h e).1 ⟨hs e he, he⟩).1
  · intro hs e he; exact ((Set.ext_iff.1 h e).2 ⟨hs e he, he⟩).1

/-- The event "no vertex of `selR r W` has its rule-edges all open". [cite: GrimmettPercolation1999, §7.3 p. 168 (7.48)] -/
def noOpenSel (E : Site d → Finset (Sym2 (Site d))) (r : ℕ) (W : Finset (Site d)) : Set (BondConfig (Site d)) :=
  ⋂ x ∈ selR r W, {ω | RuleOpen E x ω}ᶜ

/-! ## Reflections and seed rules -/

/-- The horizontal reflections: `x ↦ (ε₀ x₀, ε₁ x₁, …)` (`Site.signedPerm 1 ε`; used with
`ε 0 = 1`). [folklore] -/
def refl (ε : Fin d → ℤˣ) : Site d ≃ Site d := Site.signedPerm 1 ε

/-- Coordinates of a reflection. [folklore] -/
@[simp] theorem refl_apply (ε : Fin d → ℤˣ) (x : Site d) (i : Fin d) : refl ε x i = (ε i : ℤ) * x i := by
  simp only [refl, Site.signedPerm_apply]
  rfl

/-- Reflections are involutions. [folklore] -/
theorem refl_symm (ε : Fin d → ℤˣ) : (refl ε).symm = refl ε := by
  rw [refl, Site.signedPerm_symm]
  rfl

/-- `x` is joined to `b(0)` in `B(L,H)*`. [cite: GrimmettPercolation1999, §7.3 p. 166 (b(0) ↔ x in B(l,h)*)] -/
def Linked (d : ℕ) [NeZero d] (m L H : ℕ) (x : Site d) (ω : BondConfig (Site d)) : Prop :=
  ∃ y ∈ centralSquare d m, x ∈ openClusterIn (brickStar d L H) ω y

/-- The event `{some x ∈ F is linked with its rule-edges open}` (`X_j ≥ 1`, `Y_i ≥ 1` of p. 168 for
the rule "b(x) is a seed"). [cite: GrimmettPercolation1999, §7.3 p. 168 (X_j, Y_i)] -/
def okEventR (d : ℕ) [NeZero d] (m L H : ℕ) (E : Site d → Finset (Sym2 (Site d))) (F : Set (Site d)) :
    Set (BondConfig (Site d)) :=
  {ω | ∃ x ∈ F, Linked d m L H x ω ∧ RuleOpen E x ω}

/-- The good event for the rule `E`: a linked vertex with open rule-edges in each of the `2^{d-1}`
top subfacets and each of the `(d-1)2^{d-1}` side subfacets (Grimmett's `{B(L,H) is good}`,
p. 164, BGN's "occupied", p. 119, for the rule "b(x) is a seed", in the `B(L,H)*` form
established in the proof, p. 168). [cite: GrimmettPercolation1999, §7.3 p. 164 (good), p. 168] -/
def goodR (d : ℕ) [NeZero d] (m L H : ℕ) (E : Site d → Finset (Sym2 (Site d))) : Set (BondConfig (Site d)) :=
  (⋂ ρ : HAxis d → Bool, okEventR d m L H E (topSubfacet d L H ρ)) ∩
    ⋂ aτ : HAxis d × (HAxis d → Bool), okEventR d m L H E (sideSubfacet d L H aτ.1 aτ.2)

/-- **Valid seed rules** (the properties (i)–(iv) of the module docstring of `CleanSeeds.lean`,
with separation radius `r` and size bound `K`): rule-edges are lattice edges, avoid the edges of
`B(L,H)*`, number at most `K`, are disjoint for distinct `r`-far vertices of the top and sides,
and the rule commutes with the horizontal reflections of the brick.
[cite: GrimmettPercolation1999, §7.3 pp. 165, 168] -/
structure SeedRuleValid [NeZero d] (E : Site d → Finset (Sym2 (Site d))) (L H r K : ℕ) : Prop where
  subset_edgeSet : ∀ x ∈ top d L H ∪ sides d L H, (↑(E x) : Set (Sym2 (Site d))) ⊆ (zdGraph d).edgeSet
  disjoint_brickStar : ∀ x ∈ top d L H ∪ sides d L H,
    Disjoint (brickStar d L H).edgeSet (↑(E x) : Set (Sym2 (Site d)))
  card_le : ∀ x, (E x).card ≤ K
  disjoint_of_far : ∀ x ∈ top d L H ∪ sides d L H, ∀ y ∈ top d L H ∪ sides d L H, x ≠ y → Far r x y →
    Disjoint (E x) (E y)
  refl_equiv : ∀ ε : Fin d → ℤˣ, ε 0 = 1 → ∀ x, E (refl ε x) = (E x).map (sym2Equiv (refl ε)).toEmbedding

section Generic

variable [NeZero d] {m L H r K : ℕ} {E : Site d → Finset (Sym2 (Site d))}

/-- `okEventR` is increasing. [folklore] -/
theorem isUpperSet_okEventR (m L H : ℕ) (E : Site d → Finset (Sym2 (Site d))) (F : Set (Site d)) :
    IsUpperSet (okEventR d m L H E F) := by
  rintro ω ω' hle ⟨x, hxF, ⟨y, hy, hxy⟩, hopen⟩
  exact ⟨x, hxF, ⟨y, hy, openClusterIn_mono_config _ hle y hxy⟩, hopen.trans hle⟩

/-- `okEventR` is measurable. [folklore] -/
theorem measurableSet_okEventR (m L H : ℕ) (E : Site d → Finset (Sym2 (Site d))) (F : Set (Site d)) :
    MeasurableSet (okEventR d m L H E F) := by
  have : okEventR d m L H E F = ⋃ x ∈ F, ((⋃ y ∈ centralSquare d m, openConnVia (brickStar d L H) y x) ∩
      {ω | RuleOpen E x ω}) := by
    ext ω
    simp only [okEventR, Linked, Set.mem_setOf_eq, Set.mem_iUnion, Set.mem_inter_iff, exists_prop, openConnVia]
  rw [this]
  exact MeasurableSet.biUnion (Set.to_countable _) fun x _ =>
    (MeasurableSet.biUnion (Set.to_countable _) fun y _ => measurableSet_openConnVia _ y x).inter
      (measurableSet_ruleOpen E x)

/-- `goodR` is measurable. [folklore] -/
theorem measurableSet_goodR (m L H : ℕ) (E : Site d → Finset (Sym2 (Site d))) : MeasurableSet (goodR d m L H E) :=
  (MeasurableSet.iInter fun ρ => measurableSet_okEventR m L H E (topSubfacet d L H ρ)).inter
    (MeasurableSet.iInter fun aτ => measurableSet_okEventR m L H E (sideSubfacet d L H aτ.1 aτ.2))

/-- The seed probability: `P_p(all rule-edges of x open) = p^{|E x|} ≥ p^K` ((7.39) for Grimmett's
rule). [cite: GrimmettPercolation1999, §7.3 p. 165 (7.39)] -/
theorem pow_le_prob_ruleOpen (hV : SeedRuleValid E L H r K) {x : Site d} (hx : x ∈ top d L H ∪ sides d L H)
    (p : unitInterval) : (p : ℝ) ^ K ≤ (bondPercolation (zdGraph d) p).real {ω | RuleOpen E x ω} := by
  rw [show {ω : BondConfig (Site d) | RuleOpen E x ω} = {ω | (↑(E x) : Set (Sym2 (Site d))) ⊆ ω} from rfl,
    bondPercolation_real_setOf_subset (zdGraph d) p _ (hV.subset_edgeSet x hx)]
  exact pow_le_pow_of_le_one p.2.1 p.2.2 (hV.card_le x)

/-! ## (7.48)–(7.50) for a valid rule -/

/-- `P_p(noOpenSel) ≤ (1 - p^K)^{|selR|}` for `W ⊆ T ∪ S` (independence of the disjoint rule-edge
sets, (7.39)). [cite: GrimmettPercolation1999, §7.3 p. 165 (7.39), p. 168] -/
theorem prob_noOpenSel_le (hV : SeedRuleValid E L H r K) {W : Finset (Site d)} (hW : ↑W ⊆ top d L H ∪ sides d L H)
    (p : unitInterval) :
    (bondPercolation (zdGraph d) p).real (noOpenSel E r W) ≤ (1 - (p : ℝ) ^ K) ^ (selR r W).card := by
  have hsel := selR_spec r W
  rw [noOpenSel, bondPercolation_real_biInter_eq_prod (zdGraph d) p (selR r W)
    (fun x => {ω | RuleOpen E x ω}ᶜ) (fun x => ↑(E x))
    (fun x _ => (determinedBy_ruleOpen E x).compl) (fun x _ => (measurableSet_ruleOpen E x).compl)
    (fun x hx y hy hxy => Finset.disjoint_coe.2
      (hV.disjoint_of_far x (hW (hsel.1 hx)) y (hW (hsel.1 hy)) hxy (hsel.2.1 x hx y hy hxy))),
    ← Finset.prod_const]
  refine Finset.prod_le_prod (fun _ _ => measureReal_nonneg) fun x hx => ?_
  rw [probReal_compl_eq_one_sub (measurableSet_ruleOpen E x)]
  linarith [pow_le_prob_ruleOpen hV (hW (hsel.1 hx)) p]

/-- **The seed estimate for a valid rule** ((7.48)–(7.50)): for `Φ ω ⊆ T ∪ S` finite, depending
only on the edges of `B(L,H)*` and measurably on `ω`, and `M ≥ N₁ |B(r)|`,
`P_p(|Φ| ≥ M, no x ∈ Φ has all rule-edges open) ≤ (1 - p^K)^{N₁}`: on `{|Φ| ≥ M}` the separated
subset `selR(Φ)` has at least `N₁` vertices, their rule-edge sets are pairwise disjoint and avoid
the edges of `B(L,H)*`, so conditionally on the states of the latter they are all open independently
with probability `≥ p^K` each. [cite: GrimmettPercolation1999, §7.3 pp. 167–168 (7.48)–(7.50)] -/
theorem prob_linked_noOpen_le (hV : SeedRuleValid E L H r K) {Φ : BondConfig (Site d) → Set (Site d)}
    (hfin : ∀ ω, (Φ ω).Finite) (hsub : ∀ ω, Φ ω ⊆ top d L H ∪ sides d L H)
    (hdep : ∀ ω, Φ (ω ∩ (brickStar d L H).edgeSet) = Φ ω) (hmeas : ∀ x, MeasurableSet {ω | x ∈ Φ ω})
    {M N₁ : ℕ} (hM : N₁ * (box d r).card ≤ M) (p : unitInterval) :
    (bondPercolation (zdGraph d) p).real
        ({ω | M ≤ (hfin ω).toFinset.card} ∩ {ω | ∀ x ∈ Φ ω, ¬RuleOpen E x ω}) ≤ (1 - (p : ℝ) ^ K) ^ N₁ := by
  classical
  set A : Set (BondConfig (Site d)) := {ω | M ≤ (hfin ω).toFinset.card} with hA
  set Ψ : BondConfig (Site d) → Finset (Site d) := fun ω => (hfin ω).toFinset with hΨ
  set q : ℝ := (1 - (p : ℝ) ^ K) ^ N₁ with hq
  have hq01 : 0 ≤ 1 - (p : ℝ) ^ K ∧ 1 - (p : ℝ) ^ K ≤ 1 :=
    ⟨sub_nonneg.2 (pow_le_one₀ p.2.1 p.2.2), sub_le_self _ (pow_nonneg p.2.1 _)⟩
  have hΨsub : ∀ ω, (↑(Ψ ω) : Set (Site d)) ⊆ top d L H ∪ sides d L H := fun ω x hx => by
    rw [hΨ, Set.Finite.coe_toFinset] at hx; exact hsub ω hx
  have hpiece : ∀ W : Finset (Site d), A ∩ Ψ ⁻¹' {W} = {ω | Φ ω = ↑W} ∩ {_ω | M ≤ W.card} := by
    intro W
    ext ω
    simp only [hA, hΨ, Set.mem_inter_iff, Set.mem_preimage, Set.mem_singleton_iff, Set.mem_setOf_eq]
    constructor
    · rintro ⟨hMc, hW⟩
      exact ⟨by rw [← hW, Set.Finite.coe_toFinset], hW ▸ hMc⟩
    · rintro ⟨hW, hMc⟩
      have hW' : (hfin ω).toFinset = W := Finset.coe_injective (by rw [Set.Finite.coe_toFinset, hW])
      exact ⟨by rw [hW']; exact hMc, hW'⟩
  have hle := bondPercolation_real_inter_memDep_le (zdGraph d) p (A := A)
    (fun _ => (brickStar d L H).edgeSet)
    (fun W => ⋃ x ∈ selR r W, (↑(E x) : Set (Sym2 (Site d))))
    Ψ (noOpenSel E r)
    (fun W => by
      rw [hpiece]
      have : {ω : BondConfig (Site d) | Φ ω = ↑W} ∩ {_ω | M ≤ W.card} =
          (fun ω : BondConfig (Site d) => ω ∩ (brickStar d L H).edgeSet) ⁻¹' ({ω | Φ ω = ↑W} ∩ {_ω | M ≤ W.card}) := by
        ext ω
        simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_preimage, hdep]
      rw [this]
      exact determinedBy_preimage_inter _ _)
    (fun W => by
      rw [hpiece]
      exact (measurableSet_setStat hmeas hfin {S : Set (Site d) | S = ↑W}).inter (MeasurableSet.const _))
    (fun W => DeterminedBy.biInter (selR r W) fun x _ => (determinedBy_ruleOpen E x).compl)
    (fun W => MeasurableSet.biInter (Set.to_countable _) fun x _ => (measurableSet_ruleOpen E x).compl)
    (fun ω _ => by
      rw [Set.disjoint_iUnion₂_right]
      intro x hx
      exact hV.disjoint_brickStar x (hΨsub ω ((selR_spec r (Ψ ω)).1 hx)))
    (q := q)
    (fun ω hω => by
      refine (prob_noOpenSel_le hV (hΨsub ω) p).trans (pow_le_pow_of_le_one hq01.1 hq01.2 ?_)
      have h1 := (selR_spec r (Ψ ω)).2.2
      have h2 : M ≤ (Ψ ω).card := hω
      by_contra hlt
      push Not at hlt
      have : (selR r (Ψ ω)).card * (box d r).card < N₁ * (box d r).card :=
        Nat.mul_lt_mul_of_lt_of_le hlt le_rfl (one_le_card_box r)
      omega)
  refine le_trans (measureReal_mono ?_) (hle.trans ?_)
  · rintro ω ⟨hωA, hnone⟩
    refine ⟨hωA, ?_⟩
    simp only [Set.mem_setOf_eq, noOpenSel, Set.mem_iInter, Set.mem_compl_iff]
    intro x hx
    apply hnone
    have := (selR_spec r (Ψ ω)).1 hx
    rwa [hΨ, Set.Finite.mem_toFinset] at this
  · exact mul_le_of_le_one_right (pow_nonneg hq01.1 _) measureReal_le_one

/-- (7.48)–(7.49) for the top and a valid rule. [cite: GrimmettPercolation1999, §7.3 p. 168 (7.48)–(7.49)] -/
theorem prob_topCountGE_inter_noOpen_le (hV : SeedRuleValid E L H r K) {M N₁ : ℕ} (hM : N₁ * (box d r).card ≤ M)
    (p : unitInterval) :
    (bondPercolation (zdGraph d) p).real
        (topCountGE d m L H M ∩ {ω | ∀ x ∈ topLinked d m L H ω, ¬RuleOpen E x ω}) ≤ (1 - (p : ℝ) ^ K) ^ N₁ := by
  have h := prob_linked_noOpen_le hV (Φ := topLinked d m L H) (topLinked_finite m L H)
    (fun _ _ hx => Or.inl hx.1) (topLinked_inter_edgeSet m L H) (measurableSet_mem_topLinked m L H) hM p
  refine le_trans (measureReal_mono ?_) h
  rintro ω ⟨hU, hnone⟩
  exact ⟨mem_topCountGE_iff.1 hU, hnone⟩

/-- `V^a` only depends on the edges of `B(l,h)*`. [folklore] -/
theorem facetLinked_inter_edgeSet (a : Fin d) (m l h : ℕ) (ω : BondConfig (Site d)) :
    facetLinked d a m l h (ω ∩ (brickStar d l h).edgeSet) = facetLinked d a m l h ω := by
  simp only [facetLinked, sideLinked_inter_edgeSet]

/-- (7.50) for a facet family and a valid rule. [cite: GrimmettPercolation1999, §7.3 p. 168 (7.50)] -/
theorem prob_facetCountGE_inter_noOpen_le (hV : SeedRuleValid E L H r K) (a : Fin d) {M N₁ : ℕ}
    (hM : N₁ * (box d r).card ≤ M) (p : unitInterval) :
    (bondPercolation (zdGraph d) p).real
        ({ω | M ≤ (facetLinked_finite a m L H ω).toFinset.card} ∩
          {ω | ∀ x ∈ facetLinked d a m L H ω, ¬RuleOpen E x ω}) ≤ (1 - (p : ℝ) ^ K) ^ N₁ :=
  prob_linked_noOpen_le hV (Φ := facetLinked d a m L H) (facetLinked_finite a m L H)
    (fun _ _ hx => Or.inr hx.1.1) (facetLinked_inter_edgeSet a m L H) (measurableSet_mem_facetLinked a m L H) hM p

end Generic

end BGNd

end Percolation.Literature

end
