import Mathlib.Logic.Equiv.List
import Percolation.Literature.Basic
import Percolation.Util.Linter

/-!
# Measurability of the connection events of bond percolation (proofs for `Literature/Basic.lean`)

Sibling proof file of `Literature/Basic.lean`
(Grimmett, *Percolation*, 2nd ed. (1999), §§1.3–1.4), proving two of its statements:

* `measurableSet_openConn_holds : measurableSet_openConn` — the event `{x ↔ y}` is measurable for
  the product σ-algebra on `BondConfig V = Set (Sym2 V)` when `V` is countable: `x ↔ y` iff some
  finite list of vertices `x = v₀, v₁, …, vₙ = y` is an open walk, and "`v₀, …, vₙ` is an open
  walk" is a finite intersection of one-edge cylinder events `{s(vᵢ, vᵢ₊₁) open}`; the lists over a
  countable `V` form a countable family (`openConn_eq_iUnion`).
* `measurableSet_percolatesAt_holds : measurableSet_percolatesAt` — `{|C(x)| = ∞}` is measurable:
  `C(x)` is infinite iff for every finite set `F` of vertices some `y ∉ F` satisfies `x ↔ y`
  (`percolatesAt_eq_iInter`), a countable intersection of countable unions of the events above.

These are the routine measurability facts used implicitly throughout Grimmett 1999 (§1.3,
p. 10: "`𝓕` the σ-field of subsets of `Ω` generated by the finite-dimensional cylinders";
§1.4: `θ(p) = P_p(|C| = ∞)`); they are needed to transport `θ` along couplings
(`SubgraphMonotonicity.lean`).

A second section proves the monotone coupling of Grimmett 1999, §1.3, p. 11 (around (1.4))
and Thm. (2.1), p. 32:

* `map_configOfLabels_holds : map_configOfLabels` — under i.i.d. uniform `[0, 1]` labels `U_e`
  (`labelMeasure`), the thresholded configuration `η_p = {e ∈ E(G) | U_e ≤ p}` has law `P_p`
  (push-forward of a product measure under a coordinatewise map, `Measure.infinitePi_map_pi`,
  and the one-label computation `Leb{t ∈ [0,1] | t ≤ p} = p`).
* `theta_mono_holds : theta_mono` — `θ_x` is non-decreasing in `p` (Grimmett 1999, §1.4, p. 13;
  Thm. (2.1), p. 32, (2.3) applied to the increasing event `{|C(x)| = ∞}`): `η_{p₁} ⊆ η_{p₂}` for
  `p₁ ≤ p₂`, so `θ(p₁) = P(η_{p₁} ∈ A) ≤ P(η_{p₂} ∈ A) = θ(p₂)`.

Mathlib anchors: `SimpleGraph.reachable_iff_reflTransGen`,
`List.exists_isChain_cons_of_relationReflTransGen`, `List.relationReflTransGen_of_exists_isChain_cons`
(reachability = existence of a chain), `List.isChain_cons_cons`, `measurableSet_mem`
(one-coordinate cylinders of `Set.instMeasurableSpace`), `List.countable`, `Finset.countable`,
`Set.Infinite.exists_notMem_finset`; for the coupling `MeasureTheory.Measure.infinitePi_map_pi`,
`Real.volume_Icc`, `Real.volume_Ioc`, `unitInterval.toNNReal_add_toNNReal_symm`,
`ProbabilityTheory.setBernoulli_eq_map`.

## References

* G. Grimmett, *Percolation*, 2nd ed., Springer 1999, §1.3 (p. 10, the σ-field `𝓕`; p. 11, the
  coupling `η_p` around (1.4)), §1.4 (p. 13: (1.6) `θ(p) = P_p(|C| = ∞)`, "`θ` is a non-decreasing
  function of `p`", (1.8) `p_c = sup{p : θ(p) = 0}`), §2.1 (Thm. (2.1), p. 32; proof p. 33).
-/

namespace Percolation.Literature

open MeasureTheory

variable {V : Type*}

/-! ### Open walks along a prescribed list of vertices -/

/-- For a fixed list of vertices `a, l₀, l₁, …`, the event "consecutive vertices are joined by
open edges (and are distinct)", i.e. `a :: l` is a walk of the open graph, is measurable: by
induction on `l` it is a finite intersection of one-edge cylinders. (Grimmett 1999, §1.3, p. 10,
finite-dimensional cylinders.) [cite: GrimmettPercolation1999, §1.3 p. 10] -/
theorem measurableSet_isChain_openGraph (a : V) (l : List V) :
    MeasurableSet {ω : BondConfig V | List.IsChain (openGraph ω).Adj (a :: l)} := by
  induction l generalizing a with
  | nil => simp
  | cons b l ih =>
    have hset : {ω : BondConfig V | List.IsChain (openGraph ω).Adj (a :: b :: l)} =
        ({ω : BondConfig V | s(a, b) ∈ ω} ∩ {_ω | a ≠ b}) ∩
          {ω | List.IsChain (openGraph ω).Adj (b :: l)} := by
      ext ω
      simp only [List.isChain_cons_cons, openGraph_adj, ne_eq, Set.mem_setOf_eq,
        Set.mem_inter_iff, and_assoc]
    rw [hset]
    exact ((measurableSet_mem _).inter (MeasurableSet.const _)).inter (ih b)

/-- `{x ↔ y}` as a countable union: `x` and `y` are joined by an open path iff for some list `l`
of vertices, `x :: l` is an open walk ending at `y` (reachability is the reflexive–transitive
closure of adjacency, Mathlib's `SimpleGraph.reachable_iff_reflTransGen`, and the latter is
witnessed by chains). (Grimmett 1999, §1.3.) [cite: GrimmettPercolation1999, §1.3 p. 10] -/
theorem openConn_eq_iUnion (x y : V) :
    openConn x y = ⋃ l : List V, {ω : BondConfig V | List.IsChain (openGraph ω).Adj (x :: l) ∧
      (x :: l).getLast (List.cons_ne_nil _ _) = y} := by
  ext ω
  simp only [openConn, Set.mem_setOf_eq, Set.mem_iUnion]
  rw [SimpleGraph.reachable_iff_reflTransGen]
  constructor
  · exact List.exists_isChain_cons_of_relationReflTransGen
  · rintro ⟨l, hl, hy⟩
    exact List.relationReflTransGen_of_exists_isChain_cons l hl hy

/-- **Proof of `measurableSet_openConn`**: for countable `V` the event `{x ↔ y}` is
measurable, being a countable union (over lists of vertices) of finite intersections of one-edge
cylinder events. (Grimmett 1999, §1.3, p. 10.) [cite: GrimmettPercolation1999, §1.3 p. 10] -/
theorem measurableSet_openConn_holds : measurableSet_openConn (V := V) := by
  intro _ x y
  rw [openConn_eq_iUnion]
  refine MeasurableSet.iUnion fun l => ?_
  have hset : {ω : BondConfig V | List.IsChain (openGraph ω).Adj (x :: l) ∧
      (x :: l).getLast (List.cons_ne_nil _ _) = y} =
        {ω : BondConfig V | List.IsChain (openGraph ω).Adj (x :: l)} ∩
          {_ω | (x :: l).getLast (List.cons_ne_nil _ _) = y} := by
    ext ω; simp
  rw [hset]
  exact (measurableSet_isChain_openGraph x l).inter (MeasurableSet.const _)

/-! ### The percolation event -/

/-- `{|C(x)| = ∞}` as a countable intersection of countable unions: the open cluster of `x` is
infinite iff for every finite set `F` of vertices there is `y ∉ F` with `x ↔ y`.
(Grimmett 1999, §1.4, `θ(p) = P_p(|C| = ∞) = lim P_p(|C| ≥ n)`-type exhaustion.) [cite: GrimmettPercolation1999, §1.4 (1.9)] -/
theorem percolatesAt_eq_iInter (x : V) :
    percolatesAt x = ⋂ F : Finset V, ⋃ y ∈ (↑F : Set V)ᶜ, (openConn x y : Set (BondConfig V)) := by
  ext ω
  simp only [percolatesAt, Set.mem_setOf_eq, Set.mem_iInter, Set.mem_iUnion, Set.mem_compl_iff,
    Finset.mem_coe, exists_prop, openConn]
  constructor
  · intro hinf F
    obtain ⟨y, hy, hyF⟩ := hinf.exists_notMem_finset F
    exact ⟨y, hyF, hy⟩
  · intro h hfin
    obtain ⟨y, hyF, hy⟩ := h hfin.toFinset
    exact hyF (hfin.mem_toFinset.2 hy)

/-- **Proof of `measurableSet_percolatesAt`**: for countable `V` the event `{|C(x)| = ∞}` is
measurable (`percolatesAt_eq_iInter` and `measurableSet_openConn_holds`; the finite subsets of a
countable type form a countable family). (Grimmett 1999, §1.4.) [cite: GrimmettPercolation1999, §1.4 (1.9)] -/
theorem measurableSet_percolatesAt_holds : measurableSet_percolatesAt (V := V) := by
  intro _ x
  rw [percolatesAt_eq_iInter]
  exact MeasurableSet.iInter fun F =>
    MeasurableSet.biUnion (Set.to_countable _) fun y _ => measurableSet_openConn_holds x y

/-! ### The monotone coupling and the monotonicity of `θ`
(Grimmett 1999, §1.3 p. 11 (coupling around (1.4)), §1.4 p. 13, Thm. (2.1) p. 32) -/

section Coupling

open ProbabilityTheory
open scoped ENNReal

/-- Enlarging the set of open edges enlarges every open cluster; in particular `{|C(x)| = ∞}` and
`{x ↔ y}` are increasing events. (Grimmett 1999, §2.1, p. 32: "if `ω ∈ {|C| = ∞}` then
`ω' ∈ {|C| = ∞}` whenever `ω ≤ ω'`".) [cite: GrimmettPercolation1999, §2.1 p. 32] -/
theorem openCluster_mono {ω ω' : BondConfig V} (h : ω ⊆ ω') (x : V) :
    openCluster ω x ⊆ openCluster ω' x :=
  fun _ hy => hy.mono (SimpleGraph.fromEdgeSet_mono h)

/-- `{|C(x)| = ∞}` is an increasing event. (Grimmett 1999, §2.1, p. 32.) [cite: GrimmettPercolation1999, §2.1 p. 32] -/
theorem percolatesAt_mono {ω ω' : BondConfig V} (h : ω ⊆ ω') (x : V) (hω : ω ∈ percolatesAt x) :
    ω' ∈ percolatesAt x :=
  Set.Infinite.mono (openCluster_mono h x) hω

/-- Lebesgue measure restricted to `[0, 1]` is a probability measure (the law of one uniform
label `U_e`). (Grimmett 1999, §1.3, p. 11.) [cite: GrimmettPercolation1999, §1.3 p. 11] -/
theorem isProbabilityMeasure_volume_restrict_unitInterval :
    IsProbabilityMeasure ((volume : Measure ℝ).restrict (Set.Icc (0 : ℝ) 1)) :=
  ⟨by simp [Real.volume_Icc]⟩

/-- `labelMeasure V` (i.i.d. uniform `[0, 1]` labels, an infinite product of copies of
`Leb|[0,1]`) is a probability measure. Stated as a theorem (this is a proofs-only file); use
`have := isProbabilityMeasure_labelMeasure V` to make it available to instance search.
(Grimmett 1999, §1.3, p. 11.) [cite: GrimmettPercolation1999, §1.3 p. 11] -/
theorem isProbabilityMeasure_labelMeasure (V : Type*) :
    IsProbabilityMeasure (labelMeasure V) := by
  have := isProbabilityMeasure_volume_restrict_unitInterval
  unfold labelMeasure; infer_instance

/-- The one-label threshold map `t ↦ [e ∈ E(G) ∧ t ≤ p]` is measurable. (Grimmett 1999, §1.3,
p. 11, the indicator `η_p(e)`.) [cite: GrimmettPercolation1999, §1.3 p. 11] -/
theorem measurable_edgeThreshold (G : SimpleGraph V) (p : ℝ) (e : Sym2 V) :
    Measurable fun t : ℝ => (e ∈ G.edgeSet ∧ t ≤ p) :=
  measurable_const.and (measurableSet_setOf.1 measurableSet_Iic)

/-- `U ↦ η_p(U) = configOfLabels p U G` is measurable (each coordinate event `{e ∈ η_p}` is the
cylinder `{U_e ≤ p}` or empty). (Grimmett 1999, §1.3, p. 11.) [cite: GrimmettPercolation1999, §1.3 p. 11] -/
theorem measurable_configOfLabels (p : ℝ) (G : SimpleGraph V) :
    Measurable fun U : Sym2 V → ℝ => configOfLabels p U G :=
  measurable_set_iff.2 fun e => (measurable_edgeThreshold G p e).comp (measurable_pi_apply e)

/-- The law of one thresholded uniform label: for `p ∈ [0, 1]`, under `U_e ∼ U[0, 1]` the
indicator `[e ∈ E(G) ∧ U_e ≤ p]` has law `p δ_{(e ∈ E(G))} + (1 - p) δ_False`, i.e. Bernoulli(`p`)
on edges of `G` and `δ_False` on non-edges — exactly the one-edge factor of `setBer(E(G), p)`.
(Grimmett 1999, §1.3, p. 11: "`P(η_p(e) = 0) = 1 - p`, `P(η_p(e) = 1) = p`".) [cite: GrimmettPercolation1999, §1.3 p. 11] -/
theorem map_edgeThreshold_volume_restrict (G : SimpleGraph V) (p : unitInterval) (e : Sym2 V) :
    ((volume : Measure ℝ).restrict (Set.Icc (0 : ℝ) 1)).map
        (fun t : ℝ => (e ∈ G.edgeSet ∧ t ≤ (p : ℝ))) =
      unitInterval.toNNReal p • Measure.dirac (e ∈ G.edgeSet) +
        unitInterval.toNNReal (unitInterval.symm p) • Measure.dirac False := by
  have hp0 : (0 : ℝ) ≤ p := p.2.1
  have hp1 : (p : ℝ) ≤ 1 := p.2.2
  refine Measure.ext_of_singleton fun a => ?_
  rw [Measure.map_apply (measurable_edgeThreshold G p e) (measurableSet_singleton a),
    Measure.restrict_apply ((measurable_edgeThreshold G p e) (measurableSet_singleton a))]
  by_cases he : e ∈ G.edgeSet
  · have heT : (e ∈ G.edgeSet) = True := eq_true he
    rcases Classical.em a with ha | ha
    · obtain rfl : a = True := eq_true ha
      -- `{t ∈ [0,1] | t ≤ p} = [0, p]`, of Lebesgue measure `p`
      have hpre : (fun t : ℝ => (e ∈ G.edgeSet ∧ t ≤ (p : ℝ))) ⁻¹' {True} ∩ Set.Icc 0 1 =
          Set.Icc 0 (p : ℝ) := by
        ext t
        simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_singleton_iff, he, true_and,
          eq_iff_iff, iff_true, Set.mem_Icc]
        constructor
        · rintro ⟨h1, h2, -⟩; exact ⟨h2, h1⟩
        · rintro ⟨h1, h2⟩; exact ⟨h2, h1, h2.trans hp1⟩
      rw [hpre, Real.volume_Icc, sub_zero]
      simp [heT, ENNReal.ofReal_eq_coe_nnreal hp0]
      rfl
    · obtain rfl : a = False := eq_false ha
      -- `{t ∈ [0,1] | ¬ t ≤ p} = (p, 1]`, of Lebesgue measure `1 - p`
      have hpre : (fun t : ℝ => (e ∈ G.edgeSet ∧ t ≤ (p : ℝ))) ⁻¹' {False} ∩ Set.Icc 0 1 =
          Set.Ioc (p : ℝ) 1 := by
        ext t
        simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_singleton_iff, he, true_and,
          eq_iff_iff, iff_false, not_le, Set.mem_Icc, Set.mem_Ioc]
        constructor
        · rintro ⟨h1, -, h2⟩; exact ⟨h1, h2⟩
        · rintro ⟨h1, h2⟩; exact ⟨h1, hp0.trans h1.le, h2⟩
      rw [hpre, Real.volume_Ioc]
      simp [heT, ENNReal.ofReal_eq_coe_nnreal (sub_nonneg.2 hp1)]
      rfl
  · have heF : (e ∈ G.edgeSet) = False := eq_false he
    rcases Classical.em a with ha | ha
    · obtain rfl : a = True := eq_true ha
      have hpre : (fun t : ℝ => (e ∈ G.edgeSet ∧ t ≤ (p : ℝ))) ⁻¹' {True} ∩ Set.Icc 0 1 = ∅ := by
        ext t; simp [he]
      rw [hpre]
      simp [heF]
    · obtain rfl : a = False := eq_false ha
      have hpre : (fun t : ℝ => (e ∈ G.edgeSet ∧ t ≤ (p : ℝ))) ⁻¹' {False} ∩ Set.Icc 0 1 =
          Set.Icc 0 1 := by
        ext t; simp [he]
      rw [hpre, Real.volume_Icc, sub_zero, ENNReal.ofReal_one]
      simp only [heF, Measure.coe_add, Measure.coe_smul, Pi.add_apply, Pi.smul_apply,
        Measure.dirac_apply_of_mem (Set.mem_singleton _), ENNReal.smul_def, smul_eq_mul, mul_one]
      rw [← ENNReal.coe_add, unitInterval.toNNReal_add_toNNReal_symm, ENNReal.coe_one]

/-- **Proof of `map_configOfLabels`** (the monotone coupling has the right marginals): under
i.i.d. uniform labels, `η_p = {e ∈ E(G) | U_e ≤ p}` has law `P_p = bondPercolation G p`. Proof:
`η_p = setOf ∘ (U ↦ (e ↦ [e ∈ E(G) ∧ U_e ≤ p]))`; the push-forward of the product measure
`labelMeasure` under this coordinatewise map is the product of the one-coordinate push-forwards
(Mathlib's `Measure.infinitePi_map_pi`), and each factor is `p δ_{(e ∈ E(G))} + (1 - p) δ_False`
(`map_edgeThreshold_volume_restrict`), the factor of `setBer(E(G), p)`
(`ProbabilityTheory.setBernoulli_eq_map`). (Grimmett 1999, §1.3, p. 11, coupling around (1.4);
proof of Thm. (2.1), p. 33.) [cite: GrimmettPercolation1999, §1.3 p. 11 (coupling around (1.4))] -/
theorem map_configOfLabels_holds : map_configOfLabels (V := V) := by
  intro _ G p
  have := isProbabilityMeasure_volume_restrict_unitInterval
  have hf : (fun U : Sym2 V → ℝ => configOfLabels (p : ℝ) U G) =
      (fun q : Sym2 V → Prop => {e | q e}) ∘
        fun (U : Sym2 V → ℝ) (e : Sym2 V) => (e ∈ G.edgeSet ∧ U e ≤ (p : ℝ)) := rfl
  rw [bondPercolation, setBernoulli_eq_map, hf,
    ← Measure.map_map (g := fun q : Sym2 V → Prop => {e | q e})
      (f := fun (U : Sym2 V → ℝ) (e : Sym2 V) => (e ∈ G.edgeSet ∧ U e ≤ (p : ℝ)))
      measurable_setOf (measurable_pi_lambda _ fun e =>
        (measurable_edgeThreshold G p e).comp (measurable_pi_apply e)),
    labelMeasure, Measure.infinitePi_map_pi _ (measurable_edgeThreshold G (p : ℝ))]
  congrm Measure.map _ (Measure.infinitePi fun e => ?_)
  exact map_edgeThreshold_volume_restrict G p e

/-- **Proof of `theta_mono`**: `θ_x` is a non-decreasing function of `p`. (Grimmett 1999,
§1.4, p. 13: "Clearly `θ` is a non-decreasing function of `p` ... the most transparent proof of
this monotonicity makes use of the coupling introduced around (1.4)"; Thm. (2.1), p. 32, (2.3):
`P_{p₁}(A) ≤ P_{p₂}(A)` for `A` increasing and `p₁ ≤ p₂`, proof p. 33.) Proof as printed:
realise `P_p` as the law of `η_p` (`map_configOfLabels_holds`); `η_{p₁} ⊆ η_{p₂}` pointwise
(`configOfLabels_mono`), and `A = {|C(x)| = ∞}` is increasing (`percolatesAt_mono`) and
measurable (`measurableSet_percolatesAt_holds`), so
`θ(p₁) = P(η_{p₁} ∈ A) ≤ P(η_{p₂} ∈ A) = θ(p₂)`. [cite: GrimmettPercolation1999, Thm. (2.1) p. 32; §1.4 p. 13] -/
theorem theta_mono_holds : theta_mono (V := V) := by
  intro _ G x p q hpq
  have := isProbabilityMeasure_labelMeasure V
  have hA : MeasurableSet (percolatesAt x : Set (BondConfig V)) :=
    measurableSet_percolatesAt_holds x
  simp only [theta]
  rw [← map_configOfLabels_holds G p, ← map_configOfLabels_holds G q, measureReal_def,
    measureReal_def, Measure.map_apply (measurable_configOfLabels _ G) hA,
    Measure.map_apply (measurable_configOfLabels _ G) hA]
  refine ENNReal.toReal_mono (measure_ne_top _ _) (measure_mono fun U hU => ?_)
  exact percolatesAt_mono (configOfLabels_mono U G (Subtype.coe_le_coe.2 hpq)) x hU

end Coupling

end Percolation.Literature
