import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Basic.Real.Basic
import Mathlib.Tactic

/-!
Finite-horizon nominal MPC shift-and-append lemma (atlas obligation C3).

This module defines an absolute-time finite-horizon rollout, feasibility, and
cost for arbitrary state and input types.  A feasible plan is shifted after
its first input is removed, and a terminal feedback command is appended.  A
terminal admissibility, invariance, and cost-decrease contract then proves
feasibility and the standard one-stage cost decrease.  Optimizer existence,
closed-loop execution, convergence, and physical controller correspondence
remain separate application interfaces.
-/

open Set
open scoped BigOperators

namespace Ctrllib

variable {X U : Type*}

/-- Nominal states at the `N + 1` points generated by a length-`N` input plan.
The transition at stage `i` uses the absolute sample time `k + i`. -/
def nominalRollout (f : ℕ → X → U → X) (k : ℕ) (x : X) (n : ℕ)
    (u : Fin (n + 1) → U) : Fin (n + 2) → X :=
  fun i ↦ Fin.induction x (fun j z ↦ f (k + j.1) z (u ⟨j.1, j.2⟩)) i

@[simp]
lemma nominalRollout_zero (f : ℕ → X → U → X) (k : ℕ) (x : X) (n : ℕ)
    (u : Fin (n + 1) → U) : nominalRollout f k x n u 0 = x := rfl

lemma nominalRollout_succ (f : ℕ → X → U → X) (k : ℕ) (x : X) (n : ℕ)
    (u : Fin (n + 1) → U) (i : Fin (n + 1)) :
    nominalRollout f k x n u i.succ =
      f (k + i.1) (nominalRollout f k x n u i.castSucc) (u i) := by
  rfl

/-- Feasibility of a length-`N` plan: every predicted state/input pair obeys
its absolute-time constraint, and the terminal predicted state lies in the
terminal set at time `k + N`. -/
def nominalFeasible (f : ℕ → X → U → X) (Z : ℕ → X → U → Prop)
    (Xf : ℕ → Set X) (k : ℕ) (x : X) (n : ℕ) (u : Fin (n + 1) → U) : Prop :=
  (∀ i : Fin (n + 1), Z (k + i.1) (nominalRollout f k x n u i.castSucc) (u i)) ∧
    nominalRollout f k x n u (Fin.last (n + 1)) ∈ Xf (k + (n + 1))

/-- Finite-horizon nominal cost, with stage costs evaluated at each predicted
state and the terminal cost evaluated at the final predicted state. -/
def nominalCost (f : ℕ → X → U → X) (ell : ℕ → X → U → ℝ)
    (Vf : ℕ → X → ℝ) (k : ℕ) (x : X) (n : ℕ) (u : Fin (n + 1) → U) : ℝ :=
  (∑ i : Fin (n + 1), ell (k + i.1) (nominalRollout f k x n u i.castSucc) (u i)) +
    Vf (k + (n + 1)) (nominalRollout f k x n u (Fin.last (n + 1)))

/-- Shift the tail of a feasible plan and append the terminal feedback command.
The terminal state proof is carried explicitly because the terminal feedback
is defined only on the terminal set. -/
def nominalShiftAppend (Xf : ℕ → Set X) (κ : (k : ℕ) → Xf k → U) (k : ℕ)
    (n : ℕ) (u : Fin (n + 1) → U) (zN : X) (hzN : zN ∈ Xf (k + (n + 1))) :
    Fin (n + 1) → U :=
  Fin.lastCases (κ (k + (n + 1)) ⟨zN, hzN⟩) (fun i ↦ u i.succ)

/-- Shift-and-append for a feasible nominal plan.  The terminal contract
supplies admissibility, successor terminal membership, and terminal cost
decrease at every absolute time.  The plan length is represented as `n + 1`,
so the theorem covers every positive horizon, including the one-stage case
`n = 0`. -/
theorem nominal_shift_append
    (f : ℕ → X → U → X) (Z : ℕ → X → U → Prop) (ell : ℕ → X → U → ℝ)
    (Xf : ℕ → Set X) (Vf : ℕ → X → ℝ)
    (κ : (k : ℕ) → Xf k → U) (k : ℕ) (x : X) (n : ℕ) (u : Fin (n + 1) → U)
    (hterm : ∀ j (z : X) (hz : z ∈ Xf j),
      Z j z (κ j ⟨z, hz⟩) ∧
      f j z (κ j ⟨z, hz⟩) ∈ Xf (j + 1) ∧
      Vf (j + 1) (f j z (κ j ⟨z, hz⟩)) ≤
        Vf j z - ell j z (κ j ⟨z, hz⟩))
    (hfeas : nominalFeasible f Z Xf k x n u) :
    nominalFeasible f Z Xf (k + 1)
        (nominalRollout f k x n u (0 : Fin (n + 1)).succ) n
        (nominalShiftAppend Xf κ k n u
          (nominalRollout f k x n u (Fin.last (n + 1))) hfeas.2) ∧
      nominalCost f ell Vf (k + 1)
          (nominalRollout f k x n u (0 : Fin (n + 1)).succ) n
          (nominalShiftAppend Xf κ k n u
            (nominalRollout f k x n u (Fin.last (n + 1))) hfeas.2) ≤
        nominalCost f ell Vf k x n u -
          ell k x (u (0 : Fin (n + 1))) := by
  let z := nominalRollout f k x n u
  let xplus := z (0 : Fin (n + 1)).succ
  let zN := z (Fin.last (n + 1))
  let hzN : zN ∈ Xf (k + (n + 1)) := hfeas.2
  let uhat := nominalShiftAppend Xf κ k n u zN hzN
  have hroll : ∀ i : Fin (n + 1),
      nominalRollout f (k + 1) xplus n uhat i.castSucc = z i.succ := by
    intro i
    induction i using Fin.induction with
    | zero => rfl
    | @succ i ih =>
      have hi : i.succ.castSucc = i.castSucc.succ := Fin.ext rfl
      rw [hi]
      rw [nominalRollout_succ, ih]
      simp [uhat, nominalShiftAppend]
      change f (k + 1 + i.1) (z i.castSucc.succ) (u i.succ) =
        nominalRollout f k x n u i.succ.succ
      rw [nominalRollout_succ]
      simp only [Fin.val_succ]
      congr 1
      omega
  have hlast : nominalRollout f (k + 1) xplus n uhat (Fin.last (n + 1)) =
      f (k + (n + 1)) zN (κ (k + (n + 1)) ⟨zN, hzN⟩) := by
    rw [show Fin.last (n + 1) = (Fin.last n).succ by rfl, nominalRollout_succ,
      hroll (Fin.last n)]
    simp [uhat, nominalShiftAppend, Fin.val_last]
    dsimp [zN]
    congr 1
    omega
  have hnewfeas : nominalFeasible f Z Xf (k + 1) xplus n uhat := by
    refine ⟨?_, ?_⟩
    · intro i
      rcases i.eq_castSucc_or_eq_last with ⟨j, rfl⟩ | rfl
      · have hold := hfeas.1 j.succ
        rw [hroll j.castSucc]
        simp only [uhat, nominalShiftAppend, Fin.lastCases_castSucc]
        have hj : j.castSucc.succ = j.succ.castSucc := Fin.ext rfl
        rw [hj]
        simpa [z, Fin.val_castSucc, Fin.val_succ, Nat.add_assoc, Nat.add_comm,
          Nat.add_left_comm] using hold
      · have ht := (hterm (k + (n + 1)) zN hzN).1
        rw [hroll (Fin.last n)]
        simp only [uhat, nominalShiftAppend, Fin.lastCases_last]
        have hj : (Fin.last n).succ = Fin.last (n + 1) := rfl
        rw [hj]
        simpa [zN, z, Fin.val_last, Nat.add_assoc, Nat.add_comm,
          Nat.add_left_comm] using ht
    · rw [hlast]
      have htime : (k + 1) + (n + 1) = (k + (n + 1)) + 1 := by omega
      rw [htime]
      exact (hterm (k + (n + 1)) zN hzN).2.1
  have hnew_sum :
      (∑ i : Fin (n + 1), ell ((k + 1) + i.1)
        (nominalRollout f (k + 1) xplus n uhat i.castSucc) (uhat i)) =
        (∑ i : Fin n, ell (k + i.succ.1) (z i.succ.castSucc) (u i.succ)) +
          ell (k + (n + 1)) zN (κ (k + (n + 1)) ⟨zN, hzN⟩) := by
    rw [Fin.sum_univ_castSucc]
    congr 1
    · apply Finset.sum_congr rfl
      intro i hi
      rw [hroll i.castSucc]
      simp [uhat, nominalShiftAppend]
      congr 1
      omega
    · rw [hroll (Fin.last n)]
      simp [uhat, nominalShiftAppend]
      congr 1
      omega
  have hold_sum :
      (∑ i : Fin (n + 1), ell (k + i.1) (z i.castSucc) (u i)) =
        ell k x (u (0 : Fin (n + 1))) +
          (∑ i : Fin n, ell (k + i.succ.1) (z i.succ.castSucc) (u i.succ)) := by
    rw [Fin.sum_univ_succ]
    rfl
  have hdec := (hterm (k + (n + 1)) zN hzN).2.2
  refine ⟨hnewfeas, ?_⟩
  rw [nominalCost, nominalCost, hnew_sum, hlast, hold_sum]
  dsimp [xplus, zN]
  have htime : (k + 1) + (n + 1) = (k + (n + 1)) + 1 := by omega
  rw [htime]
  linarith

end Ctrllib
